import type { Task, TaskComment } from './fetcher.js';

export type Readiness = 'ok' | 'needs_info';

/** Minimum number of characters in the cleaned description to be considered non-trivial. */
export const MIN_DESCRIPTION_CHARS = 30;

/** XML tag name used by Vanguard to wrap generated tech specs. */
export const SPEC_TAG = 'tech_spec';

/**
 * Placeholder bullet texts (lowercased) drawn from the GitHub issue template's example checkboxes.
 * A criteria section is considered placeholder-only when every non-empty bullet matches one of these.
 * Stored lowercased so matching is case-insensitive (compare against `bulletText.toLowerCase()`).
 */
export const PLACEHOLDER_CRITERIA_LINES: ReadonlySet<string> = new Set([
  'feature x functions as intended.',
  'unit tests are written or updated to cover the new changes.',
  'the existing ci pipeline passes successfully.',
  'optional: relevant documentation is updated.',
]);

/** Regex matching an Acceptance Criteria heading (case-insensitive, allows emoji/markdown prefix). */
const AC_HEADING_RE = /^#{1,6}\s.*acceptance\s+criteria/i;

/** Regex matching any markdown heading line (`# ...`). */
const HEADING_RE = /^#{1,6}\s/;

/** Regex matching a checklist or bullet line: `- [ ]`, `- [x]`, `-`, or `*` followed by content. */
const BULLET_RE = /^(?:-\s*\[[ xX]\]\s*|-\s+|\*\s+)(.*)/;

/** Strip all HTML comments (`<!-- ... -->`) from a string, including multi-line ones. */
export function stripHtmlComments(text: string): string {
  return text.replace(/<!--[\s\S]*?-->/g, '');
}

/**
 * Returns true when the text contains an Acceptance-Criteria heading followed by
 * at least one bullet line with real (non-placeholder) content.
 */
export function hasRealAcceptanceCriteria(text: string): boolean {
  const lines = text.split('\n');
  let inAcSection = false;
  let foundNonPlaceholderBullet = false;
  let foundAnyBullet = false;

  for (const raw of lines) {
    const line = raw.trimEnd();

    if (AC_HEADING_RE.test(line)) {
      inAcSection = true;
      continue;
    }

    // A new heading terminates the AC section.
    if (inAcSection && HEADING_RE.test(line) && !AC_HEADING_RE.test(line)) {
      break;
    }

    if (!inAcSection) {
      continue;
    }

    const match = BULLET_RE.exec(line);
    if (match === null) {
      continue;
    }

    const bulletText = (match[1] ?? '').trim();
    if (bulletText === '') {
      continue;
    }

    foundAnyBullet = true;
    if (!PLACEHOLDER_CRITERIA_LINES.has(bulletText.toLowerCase())) {
      foundNonPlaceholderBullet = true;
      break;
    }
  }

  return foundAnyBullet && foundNonPlaceholderBullet;
}

/**
 * Returns true when a comment was generated by Vanguard: its body contains the `<tech_spec` opening
 * tag. Strict marker — does NOT match a human-written comment that merely has an Acceptance Criteria
 * heading. Use this for idempotency guards to avoid falsely skipping generation.
 *
 * @param comment - The task comment to inspect.
 * @returns `true` when the body contains the Vanguard `<tech_spec` marker; `false` otherwise.
 */
export function isVanguardSpec(comment: TaskComment): boolean {
  return comment.body.includes(`<${SPEC_TAG}`);
}

/**
 * Deterministic (no LLM) gate that checks whether a task is ready to be processed.
 *
 * - `spec` mode: requires a non-trivial description (>= MIN_DESCRIPTION_CHARS chars after
 *   stripping HTML comments).
 * - `agent` mode: additionally requires either real acceptance-criteria bullets OR a
 *   spec comment in `task.comments`.
 *
 * Returns `'ok'` when the task meets the bar, `'needs_info'` otherwise.
 */
export function assessTaskReadiness(task: Task, mode: 'spec' | 'agent'): Readiness {
  const cleaned = stripHtmlComments(task.description).trim();

  if (cleaned.length < MIN_DESCRIPTION_CHARS) {
    return 'needs_info';
  }

  if (mode === 'spec') {
    return 'ok';
  }

  // agent mode: also need real criteria OR a spec comment.
  const hasRealCriteria = hasRealAcceptanceCriteria(cleaned);
  if (hasRealCriteria) {
    return 'ok';
  }

  const hasSpecComment = task.comments.some((c) => c.body.trim() !== '' && (isVanguardSpec(c) || hasRealAcceptanceCriteria(c.body)));
  if (hasSpecComment) {
    return 'ok';
  }

  return 'needs_info';
}
